### ISSUE TITLE
[package] qt/6.3.1: fails to find freetype

### ISSUE THREAD

**Issue by thejinx0r** [conan-io/conan-center-index#14327]
### Description

I'm trying to build qt 6.3.1 with the webengine enabled and I keep getting an error that it can't find freetype.
I can see that the `FindFreetype.cmake` is generated, but that it comes down to `harfbuzz` links against freetype, but it's not finding it. It's as if harfbuzz 

### Package and Environment Details

* Package Name/Version: **zlib/1.2.8**
* Operating System+version: **Linux Ubuntu 18.04**
* Compiler+version: **GCC 8**
* Docker image: **conanio/gcc8**
* Conan version: **conan 1.18.0**
* Python version: **Python 3.7.4**

### Conan profile

[settings]
arch=x86_64
arch_build=x86_64
build_type=Debug
compiler=Visual Studio
compiler.runtime=MDd
compiler.version=17
os=Windows
os_build=Windows
[options]
[build_requires]
[env]

### Steps to reproduce

`conan install . --build missing -s build_type=Debug --install-folder dependencies/windows/debug --settings compiler.version=17  -s "compiler=Visual Studio"`

where the conanfile.py is just below. Sorry for the formmating

<details><summary>conanfile.py</summary>

```

from conans import ConanFile
from conans.errors import ConanException
required_conan_version = ">=1.54.0"

class DragonflyConan(ConanFile):
    generators = "cmake", "cmake_paths", "cmake_find_package"
    settings = "os", "build_type"

    def requirements(self):
        # pydevd_pycharm.settrace('localhost', port=62421, stdoutToServer=True, stderrToServer=True)
        self.requires("qt/6.3.1")
        self.requires("icu/70.1")
        self._add_requirements_to_manage_conflicts()

    def _add_requirements_to_manage_conflicts(self):
        pass
        ## qt / opencascade
        self.requires('freetype/2.12.1')
        ## qt / cpr
        self.requires("zlib/1.2.13")
        ## qt / cpr
        #self.requires("zstd/1.5.2")
        ## qt / cpr
        #self.requires("openssl/1.1.1s")

    @property
    def _is_windows(self) -> bool:
        return self.settings.get_safe("os") == 'Windows'

    @property
    def _is_linux(self) -> bool:
        return self.settings.get_safe("os") == 'Linux'

    @property
    def _is_debug_build(self) -> bool:
        return self.settings.get_safe("build_type") == "Debug"


    def configure(self):
        self.options["qt"].shared = True
        self.options["qt"].qttools = not self._is_debug_build
        self.options["qt"].qtwebchannel = True
        self.options["qt"].qtwebengine = True
        self.options["qt"].qtwebsockets = True
        self.options["qt"].qt5compat= True
        self.options["qt"].qtsvg= True
        self.options["qt"].qtimageformats= True
        self.options["qt"].qtscxml= True
        self.options["qt"].qtmultimedia= False
        self.options["qt"].qtmultimedia= False
        self.options["qt"].qtactiveqt= False
        self.options["qt"].qtdatavis3d= False
        self.options["qt"].qtdeclarative= False
        self.options["qt"].qtlanguageserver= False
        self.options["qt"].qtshadertools= False
        self.options["qt"].qtcoap= False
        self.options["qt"].qtcharts= False
        self.options["qt"].qtconnectivity= False
        self.options["qt"].qtvirtualkeyboard= False
        self.options["qt"].qtwayland= self._is_linux
        self.options["qt"].qtserialbus= False
        self.options["qt"].qtsensors= False
        self.options["qt"].with_sqlite3 = False
        self.options["qt"].with_mysql = False
        self.options["qt"].with_pq = False
        self.options["qt"].with_odbc = False
        self.options["qt"].with_libjpeg = "libjpeg"
        self.options["qt"].with_libpng = True
        self.options["qt"].with_zstd = True
        self.options["qt"].with_md4c= True
        self.options["qt"].with_freetype = True
        self.options["qt"].with_glib = False
        # self.options["qt"].with_icu  = True
        self.options["qt"].gui = True
        self.options["qt"].widgets = True

        self.options["harfbuzz"].with_glib = False # disable glib to prevent gpl dependencies
        #self.options["harfbuzz"].shared = False
        #self.options["harfbuzz"].with_icu = True

        #self.options["cpr"].shared = True
        #self.options["freetype"].shared = False
        #self.options["glew"].shared = True
        #self.options["zstd"].shared = True
        #self.options["zlib"].shared = True
        self.options["openssl"].shared = True
        self.options["openssl"].no_tests=True
        self.options["icu"].shared = True
        ##self.options["tk"].shared = True
        #self.options["tcl"].shared = True
        #self.options["opencascade"].shared = True
        #self.options["opencascade"].with_tk =  False
        #self.options["opencascade"].with_opengl =  False
        #if not self._is_windows:
        #    self.options["icu"].data_packaging = "library"
```
</details>

### Logs

<details><summary>Click to expand log</summary>

I couldn't paste the whole log, so you find the whole thing here: https://controlc.com/65658d02
Here's the snippet of the log that I think is relevant:
```
-- Configuring done
CMake Error at C:/.conan/ada86a/1/Findharfbuzz.cmake:62 (set_property):
  The link interface of target "CONAN_LIB::harfbuzz_harfbuzz" contains:

    Freetype::Freetype

  but the target was not found.  Possible reasons include:

    * There is a typo in the target name.
    * A find_package call is missing for an IMPORTED target.
    * An ALIAS target is missing.

Call Stack (most recent call first):
  C:/.conan/ada86a/1/Findharfbuzz.cmake:128 (conan_package_library_targets)
  qtbase/cmake/FindWrapSystemHarfbuzz.cmake:9 (find_package)
  qtbase/cmake/QtFindPackageHelpers.cmake:130 (find_package)
  qtbase/src/gui/configure.cmake:45 (qt_find_package)
  qtbase/cmake/QtFeature.cmake:573 (include)
  qtbase/src/CMakeLists.txt:12 (qt_feature_evaluate_features)


CMake Error at C:/.conan/ada86a/1/Findharfbuzz.cmake:163 (set_property):
  The link interface of target "harfbuzz::harfbuzz" contains:

    Freetype::Freetype

  but the target was not found.  Possible reasons include:

    * There is a typo in the target name.
    * A find_package call is missing for an IMPORTED target.
    * An ALIAS target is missing.

Call Stack (most recent call first):
  qtbase/cmake/FindWrapSystemHarfbuzz.cmake:9 (find_package)
  qtbase/cmake/QtFindPackageHelpers.cmake:130 (find_package)
  qtbase/src/gui/configure.cmake:45 (qt_find_package)
  qtbase/cmake/QtFeature.cmake:573 (include)
  qtbase/src/CMakeLists.txt:12 (qt_feature_evaluate_features)


-- Generating done
CMake Warning:
  Manually-specified variables were not used by the project:

    BUILD_qtqa
    BUILD_qtrepotools
    CMAKE_EXPORT_NO_PACKAGE_REGISTRY
    FEATURE_sqlite


CMake Generate step failed.  Build files cannot be regenerated correctly.
```
</details>

**Comment by ericLemanissier** [comment]
QtWebengine needs QtQuick, and during you build qtquick is not built because `Qt Quick modules not built due to not finding the qtshadertools 'qsb' tool.`. So you should set ` self.options["qt"].qtshadertools= True`
this should fix this error:
```
Configuring submodule 'qtdeclarative'
-- Could NOT find Qt6ShaderTools (missing: Qt6ShaderTools_DIR)
CMake Warning at C:/.conan/f2038d/1/qtbase/lib/cmake/Qt6/Qt6Config.cmake:263 (message):
  Failed to find Qt component "ShaderTools".

  Expected Config file at
  "C:/.conan/f2038d/1/qtbase/lib/cmake/Qt6ShaderTools/Qt6ShaderToolsConfig.cmake"
  does NOT exist

Call Stack (most recent call first):
  qtdeclarative/CMakeLists.txt:41 (find_package)
```
and then its consequences:
```
Configuring submodule 'qtscxml'
-- Could NOT find Qt6QuickTest (missing: Qt6QuickTest_DIR)
CMake Warning at C:/.conan/f2038d/1/qtbase/lib/cmake/Qt6/Qt6Config.cmake:263 (message):
  Failed to find Qt component "QuickTest".

  Expected Config file at
  "C:/.conan/f2038d/1/qtbase/lib/cmake/Qt6QuickTest/Qt6QuickTestConfig.cmake"
  does NOT exist

Call Stack (most recent call first):
  qtscxml/CMakeLists.txt:12 (find_package)
```
```
Configuring submodule 'qtwebsockets'
-- Could NOT find Qt6Quick (missing: Qt6Quick_DIR)
CMake Warning at C:/.conan/f2038d/1/qtbase/lib/cmake/Qt6/Qt6Config.cmake:263 (message):
  Failed to find Qt component "Quick".

  Expected Config file at
  "C:/.conan/f2038d/1/qtbase/lib/cmake/Qt6Quick/Qt6QuickConfig.cmake" does
  NOT exist

Call Stack (most recent call first):
  qtwebsockets/CMakeLists.txt:17 (find_package)


-- Could NOT find Qt6QuickTest (missing: Qt6QuickTest_DIR)
CMake Warning at C:/.conan/f2038d/1/qtbase/lib/cmake/Qt6/Qt6Config.cmake:263 (message):
  Failed to find Qt component "QuickTest".

  Expected Config file at
  "C:/.conan/f2038d/1/qtbase/lib/cmake/Qt6QuickTest/Qt6QuickTestConfig.cmake"
  does NOT exist

Call Stack (most recent call first):
  qtwebsockets/CMakeLists.txt:17 (find_package)
```
```
Configuring submodule 'qtwebchannel'
-- Could NOT find Qt6Quick (missing: Qt6Quick_DIR)
CMake Warning at C:/.conan/f2038d/1/qtbase/lib/cmake/Qt6/Qt6Config.cmake:263 (message):
  Failed to find Qt component "Quick".

  Expected Config file at
  "C:/.conan/f2038d/1/qtbase/lib/cmake/Qt6Quick/Qt6QuickConfig.cmake" does
  NOT exist

Call Stack (most recent call first):
  qtwebchannel/CMakeLists.txt:17 (find_package)


-- Could NOT find Qt6QuickTest (missing: Qt6QuickTest_DIR)
CMake Warning at C:/.conan/f2038d/1/qtbase/lib/cmake/Qt6/Qt6Config.cmake:263 (message):
  Failed to find Qt component "QuickTest".

  Expected Config file at
  "C:/.conan/f2038d/1/qtbase/lib/cmake/Qt6QuickTest/Qt6QuickTestConfig.cmake"
  does NOT exist

Call Stack (most recent call first):
  qtwebchannel/CMakeLists.txt:17 (find_package)
```

**Comment by thejinx0r** [comment]
Thanks for looking into it!
It looked like they were just warnings and were safe to ignore as I don't plan on using qt quick.

In any case, I tried enabling the qtshadertools just to be on the cautious side and I still have the same underlying error.

Here's the full log again: https://controlc.com/018cba6c

Here's the part I think is relevant:

<details>
<summary> relevant portion of the log </summary>

```
-- Configuring done
CMake Error at C:/.conan/be9ee0/1/Findharfbuzz.cmake:62 (set_property):
  The link interface of target "CONAN_LIB::harfbuzz_harfbuzz" contains:

    Freetype::Freetype

  but the target was not found.  Possible reasons include:

    * There is a typo in the target name.
    * A find_package call is missing for an IMPORTED target.
    * An ALIAS target is missing.

Call Stack (most recent call first):
  C:/.conan/be9ee0/1/Findharfbuzz.cmake:128 (conan_package_library_targets)
  qtbase/cmake/FindWrapSystemHarfbuzz.cmake:9 (find_package)
  qtbase/cmake/QtFindPackageHelpers.cmake:130 (find_package)
  qtbase/src/gui/configure.cmake:45 (qt_find_package)
  qtbase/cmake/QtFeature.cmake:573 (include)
  qtbase/src/CMakeLists.txt:12 (qt_feature_evaluate_features)


CMake Error at C:/.conan/be9ee0/1/Findharfbuzz.cmake:163 (set_property):
  The link interface of target "harfbuzz::harfbuzz" contains:

    Freetype::Freetype

  but the target was not found.  Possible reasons include:

    * There is a typo in the target name.
    * A find_package call is missing for an IMPORTED target.
    * An ALIAS target is missing.

Call Stack (most recent call first):
  qtbase/cmake/FindWrapSystemHarfbuzz.cmake:9 (find_package)
  qtbase/cmake/QtFindPackageHelpers.cmake:130 (find_package)
  qtbase/src/gui/configure.cmake:45 (qt_find_package)
  qtbase/cmake/QtFeature.cmake:573 (include)
  qtbase/src/CMakeLists.txt:12 (qt_feature_evaluate_features)


-- Generating done
```

</details>


<details><summary>and my conan file</summary>

```python
import pydevd_pycharm
from conans import ConanFile
from conans.errors import ConanException
required_conan_version = ">=1.54.0"

class DragonflyConan(ConanFile):
    generators = "cmake", "cmake_paths", "cmake_find_package"
    settings = "os", "build_type"

    def requirements(self):
        # pydevd_pycharm.settrace('localhost', port=62421, stdoutToServer=True, stderrToServer=True)
        self.requires("qt/6.3.1")
        self.requires("icu/70.1") # force the use of icu 70.1 for the python distro
        self._add_requirements_to_manage_conflicts()

    def _add_requirements_to_manage_conflicts(self):
        # qt / opencascade
        self.requires('freetype/2.12.1')
        # qt / cpr
        self.requires("zlib/1.2.13")
        # qt / cpr
        self.requires("zstd/1.5.2")
        # qt / cpr
        self.requires("openssl/1.1.1s")

    @property
    def _is_windows(self) -> bool:
        return self.settings.get_safe("os") == 'Windows'

    @property
    def _is_linux(self) -> bool:
        return self.settings.get_safe("os") == 'Linux'

    @property
    def _is_debug_build(self) -> bool:
        return self.settings.get_safe("build_type") == "Debug"


    def configure(self):
        self.options["qt"].shared = True
        self.options["qt"].qttools = not self._is_debug_build
        self.options["qt"].qtwebchannel = True
        self.options["qt"].qtwebengine = True
        self.options["qt"].qtwebsockets = True
        self.options["qt"].qt5compat= True
        self.options["qt"].qtsvg= True
        self.options["qt"].qtimageformats= True
        self.options["qt"].qtscxml= True
        self.options["qt"].qtmultimedia= False
        self.options["qt"].qtactiveqt= False
        self.options["qt"].qtdatavis3d= False
        self.options["qt"].qtdeclarative= False
        self.options["qt"].qtlanguageserver= False
        self.options["qt"].qtshadertools= True  # needed for the web engine and for certain aspects of font rendering
        self.options["qt"].qtcoap= False
        self.options["qt"].qtcharts= False
        self.options["qt"].qtconnectivity= False
        self.options["qt"].qtvirtualkeyboard= False
        self.options["qt"].qtwayland= self._is_linux
        self.options["qt"].qtserialbus= False
        self.options["qt"].qtsensors= False
        self.options["qt"].with_sqlite3 = False
        self.options["qt"].with_mysql = False
        self.options["qt"].with_pq = False
        self.options["qt"].with_odbc = False
        self.options["qt"].with_libjpeg = "libjpeg"
        self.options["qt"].with_libpng = True
        self.options["qt"].with_zstd = True
        self.options["qt"].with_md4c= True
        self.options["qt"].with_freetype = True
        self.options["qt"].with_glib = False
        if not self._is_windows:
            self.options["qt"].with_icu  = True
        self.options["qt"].gui = True
        self.options["qt"].widgets = True

        self.options["harfbuzz"].with_glib = False # disable glib to prevent gpl dependencies
        #self.options["harfbuzz"].shared = False
        #self.options["harfbuzz"].with_icu = True

        self.options["cpr"].shared = True
        self.options["freetype"].shared = False
        self.options["glew"].shared = True
        self.options["zstd"].shared = True
        self.options["zlib"].shared = True
        self.options["openssl"].shared = True
        self.options["openssl"].no_tests=True
        self.options["icu"].shared = True
        #self.options["tk"].shared = True
        self.options["tcl"].shared = True
        self.options["opencascade"].shared = True
        self.options["opencascade"].with_tk =  False
        self.options["opencascade"].with_opengl =  False
        if not self._is_windows:
            self.options["icu"].data_packaging = "library"
        
```

</details>

**Comment by ericLemanissier** [comment]
mmmm, ok, so this is the same problem as https://github.com/conan-io/conan-center-index/issues/13144
The solution is to do https://github.com/ericLemanissier/conan-center-index/commit/8d455a7414d517713fe8961a3a405cd827b737cd, but it unfortunately breaks a several other use cases. If you have the time to try it out (and maybe fix what's broken ?), don't hesitate !

**Comment by thejinx0r** [comment]
I confirm that I use a conda environments and installed conan in one of them.

I tried to apply the changes from the diff and now it works.

I tried a few things like setting the variables that control where it looks for packages, it didn't yield anything successful.
I'm abit out of my depth here on what the actual problem is and how to tackle fixing it.

Just to keep everything centralized, I'm going close this issue as it is resolved and just keep an eye out on #13144.
