### ISSUE TITLE
[package] fltk/1.3.9: fais to find installed libxft

### ISSUE THREAD

**Issue by basiliscos** [conan-io/conan-center-index#29240]
### Description

there is a profile option `fltk/*:with_xft=True`,  and it is successfully installed however fltk fails to find it

```
...
libxft/2.3.8: package(): Packaged 1 file: COPYING
libxft/2.3.8: package(): Packaged 1 '.so' file: libXft.so
libxft/2.3.8: package(): Packaged 1 '.2' file: libXft.so.2
libxft/2.3.8: package(): Packaged 1 '.8' file: libXft.so.2.3.8
libxft/2.3.8: package(): Packaged 2 '.h' files: XftCompat.h, Xft.h
libxft/2.3.8: Created package revision d3f9161b53ccb6658bced1d48a077f08
libxft/2.3.8: Package '5bae10d3a765c850cccf71601d3686dd59eb4916' created
libxft/2.3.8: Full package reference: libxft/2.3.8#5a86906f15dcf469406c4b186410bf0b:5bae10d3a765c850cccf71601d3686dd59eb4916#d3f9161b53ccb6658bced1d48a077f08
libxft/2.3.8: Package folder /root/.conan2/p/b/libxf81d9580846d6c/p
...

...
[ 27%] Building CXX object src/CMakeFiles/fltk_SHARED.dir/Fl_Preferences.cxx.o
/root/.conan2/p/b/fltkd22c8b90f9aed/b/src/src/Fl_PostScript.cxx:31:10: fatal error: X11/Xft/Xft.h: No such file or directory
   31 | #include <X11/Xft/Xft.h>
      |          ^~~~~~~~~~~~~~~
compilation terminated.
gmake[2]: *** [src/CMakeFiles/fltk_SHARED.dir/b
```

full logs are available on https://sourcecraft.dev/the-dmol/syncspirit/cicd/runs/2

### Package and Environment Details

* Package Name/Version: **fltk/1.3.9**
* Operating System+version: **Linux Ubuntu 22.04**
* Conan version: **conan 2.24**

### Conan profile

```
[settings]
arch=x86_64
build_type=Release
compiler=gcc
compiler.cppstd=20
compiler.libcxx=libstdc++11
compiler.version=11
os=Linux

[options]
*/*:shared=True
fltk/*:with_xft=True
fltk/*:with_gl=False
boost/*:magic_autolink=False
boost/*:visibility=hidden
boost/*:header_only=False
boost/*:without_serialization=True
boost/*:without_graph=True
boost/*:without_fiber=True
boost/*:without_log=True
boost/*:without_math=True
boost/*:without_process=True
boost/*:without_stacktrace=True
boost/*:without_test=True
boost/*:without_wave=True
boost/*:without_cobalt=True
boost/*:without_contract=True
boost/*:without_coroutine=True
boost/*:without_filesystem=True
boost/*:without_json=True
boost/*:without_regex =True
pugixml/*:no_exceptions=True
rotor/*:enable_asio=True
rotor/*:enable_thread=True
rotor/*:enable_fltk=True
```

### Steps to reproduce

```
conan install --build=missing --profile=linux-native --output-folder . -s build_type=Debug -o '&:shared=True' ..
```
### Logs

https://sourcecraft.dev/the-dmol/syncspirit/cicd/runs/2

**Comment by uilianries** [comment]
@basiliscos Hello! Thank you for reporting your case. I can reproduce it locally as well. 

Also, I see the version 1.4.4 (available in Conan Center) does not result in the same error, but it passes instead. It seems be connected to how the upstream include libxft: [fltk-1.4.4-linux-amd64-gcc11-release-static-xft.log](https://github.com/user-attachments/files/24435490/fltk-1.4.4-linux-amd64-gcc11-release-static-xft.log)

Could you please update to the version 1.4.4 instead, available in Conan Center? 

https://conan.io/center/recipes/fltk?version=1.4.4

Regards!

**Comment by basiliscos** [comment]
@uilianries sorry, I can't use fltk `1.4.4`, because it contains some silly bug, when I try to use fltk-tree widget:

```
[ 84%] Building CXX object src/ui-fltk/CMakeFiles/syncspirit-fltk.dir/app_supervisor.cpp.obj
In file included from /home/b/.conan2/p/b/fltk7f3aad371ca7f/p/include/FL/fl_draw.H:26,
                 from /home/b/.conan2/p/b/fltk7f3aad371ca7f/p/include/FL/Fl_Tree_Item.H:9,
                 from /tmp/syncspirit/src/ui-fltk/tree_item.h:10,
                 from /tmp/syncspirit/src/ui-fltk/presence_item.h:6,
                 from /tmp/syncspirit/src/ui-fltk/presence_item/folder.h:6,
                 from /tmp/syncspirit/src/ui-fltk/app_supervisor.cpp:7:
/home/b/.conan2/p/b/fltk7f3aad371ca7f/p/include/FL/Fl_Graphics_Driver.H:398:21: error: function 'Fl_Font_Descriptor::~Fl_Font_Descriptor()' definition is marked dllimport
  398 |   virtual FL_EXPORT ~Fl_Font_Descriptor() {}
      |                     ^
make[3]: *** [src/ui-fltk/CMakeFiles/syncspirit-fltk.dir/build.make:80: src/ui-fltk/CMakeFiles/syncspirit-fltk.dir/app_supervisor.cpp.obj] Error 1
```

It is already fixed in `master` but no ftlk has been released yet.

**Comment by uilianries** [comment]
> It is already fixed in master but no ftlk has been released yet.

Have you checked with the upstream on the availability of a new release? Do you know which PR/commit fixed this error for 1.4.4?

**Comment by basiliscos** [comment]
> Have you checked with the upstream on the availability of a new release?

yep, I receive notifications upon new releases. So, there are no new releases since v1.4.4

> Do you know which PR/commit fixed this error for 1.4.4?

I didn't tracked it, just checked that buggy sources (destructor) was moved out of `FL/fl_draw.H` into some `.cpp` file

**Comment by uilianries** [comment]
> yep, I receive notifications upon new releases. So, there are no new releases since v1.4.4

I meant, open issues asking a new release. Could you please check it? You also can ask the upstream to release a new patch as well. As far as I see, you are dealing with a upstream bug, as the recipe is behaving according to project.

**Comment by basiliscos** [comment]
done, https://github.com/fltk/fltk/issues/1357

**Comment by uilianries** [comment]
@basiliscos Hello! As version 1.4.5 is already available in the Conan Center (https://conan.io/center/recipes/fltk?version=1.4.5), I believe this issue can be closed as both your reported issue is not fixed and your original report is fixed in 1.4.5 too. Regards.
